# Generated by Django 6.0 on 2025-12-10 07:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('fullName', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254, unique=True)),
                ('phone', models.CharField(max_length=15)),
                ('userType', models.CharField(max_length=20)),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('emergencyContact', models.CharField(blank=True, max_length=20, null=True)),
                ('linkedAccounts', models.JSONField(blank=True, default=list)),
                ('vehicleType', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicleNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('idProof', models.CharField(blank=True, max_length=50, null=True)),
                ('idNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('availability', models.CharField(blank=True, max_length=50, null=True)),
                ('specialization', models.CharField(blank=True, max_length=50, null=True)),
                ('medicalLicense', models.CharField(blank=True, max_length=50, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('consultationFee', models.IntegerField(blank=True, null=True)),
                ('availableHours', models.TextField(blank=True, null=True)),
                ('storeName', models.CharField(blank=True, max_length=200, null=True)),
                ('businessType', models.CharField(blank=True, max_length=50, null=True)),
                ('gstNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('storeAddress', models.TextField(blank=True, null=True)),
                ('businessLicense', models.CharField(blank=True, max_length=100, null=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('isVerified', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
