# Generated by Django 6.0 on 2025-12-10 11:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='address',
        ),
        migrations.RemoveField(
            model_name='user',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='user',
            name='availableHours',
        ),
        migrations.RemoveField(
            model_name='user',
            name='businessLicense',
        ),
        migrations.RemoveField(
            model_name='user',
            name='businessType',
        ),
        migrations.RemoveField(
            model_name='user',
            name='consultationFee',
        ),
        migrations.RemoveField(
            model_name='user',
            name='dateOfBirth',
        ),
        migrations.RemoveField(
            model_name='user',
            name='emergencyContact',
        ),
        migrations.RemoveField(
            model_name='user',
            name='experience',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='user',
            name='gstNumber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='idNumber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='idProof',
        ),
        migrations.RemoveField(
            model_name='user',
            name='linkedAccounts',
        ),
        migrations.RemoveField(
            model_name='user',
            name='medicalLicense',
        ),
        migrations.RemoveField(
            model_name='user',
            name='qualifications',
        ),
        migrations.RemoveField(
            model_name='user',
            name='specialization',
        ),
        migrations.RemoveField(
            model_name='user',
            name='storeAddress',
        ),
        migrations.RemoveField(
            model_name='user',
            name='storeName',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vehicleNumber',
        ),
        migrations.RemoveField(
            model_name='user',
            name='vehicleType',
        ),
        migrations.AlterField(
            model_name='user',
            name='phone',
            field=models.CharField(max_length=15, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='userType',
            field=models.CharField(choices=[('user', 'User'), ('doctor', 'Doctor'), ('vendor', 'Vendor'), ('delivery', 'DeliveryPartner')], max_length=20),
        ),
        migrations.CreateModel(
            name='DeliveryPartnerProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vehicleType', models.CharField(blank=True, max_length=50, null=True)),
                ('vehicleNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('idProof', models.CharField(blank=True, max_length=50, null=True)),
                ('idNumber', models.CharField(blank=True, max_length=50, null=True)),
                ('availability', models.CharField(blank=True, max_length=50, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='deliverypartner', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specialization', models.CharField(blank=True, max_length=50, null=True)),
                ('medicalLicense', models.CharField(blank=True, max_length=50, null=True)),
                ('qualifications', models.TextField(blank=True, null=True)),
                ('experience', models.IntegerField(blank=True, null=True)),
                ('consultationFee', models.IntegerField(blank=True, null=True)),
                ('availableHours', models.TextField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='doctor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='PatientProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dateOfBirth', models.DateField(blank=True, null=True)),
                ('gender', models.CharField(blank=True, max_length=20, null=True)),
                ('address', models.TextField(blank=True, null=True)),
                ('emergencyContact', models.CharField(blank=True, max_length=20, null=True)),
                ('linkedAccounts', models.JSONField(blank=True, default=list)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='patient', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='VendorProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('storeName', models.CharField(blank=True, max_length=200, null=True)),
                ('businessType', models.CharField(blank=True, max_length=50, null=True)),
                ('gstNumber', models.CharField(blank=True, max_length=30, null=True)),
                ('storeAddress', models.TextField(blank=True, null=True)),
                ('businessLicense', models.CharField(blank=True, max_length=100, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='vendor', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
