# Generated by Django 6.0 on 2025-12-11 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_deliveryuser_doctoruser_patientuser_vendoruser_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deliveryuser',
            name='aadhaarPhoto',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/aadhaar/'),
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='drivingLicensePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/license/'),
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='profilePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/profile/'),
        ),
        migrations.AlterField(
            model_name='deliveryuser',
            name='availability',
            field=models.CharField(blank=True, default='Available', max_length=50),
        ),
        migrations.AlterField(
            model_name='deliveryuser',
            name='idNumber',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='deliveryuser',
            name='idProof',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='doctoruser',
            name='experience',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
