# Generated by Django 6.0 on 2025-12-11 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_deliveryuser_aadhaarphoto_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='deliveryuser',
            name='aadhaarPhoto',
        ),
        migrations.RemoveField(
            model_name='deliveryuser',
            name='availability',
        ),
        migrations.RemoveField(
            model_name='deliveryuser',
            name='drivingLicensePhoto',
        ),
        migrations.RemoveField(
            model_name='deliveryuser',
            name='idNumber',
        ),
        migrations.RemoveField(
            model_name='deliveryuser',
            name='idProof',
        ),
        migrations.RemoveField(
            model_name='deliveryuser',
            name='profilePhoto',
        ),
        migrations.RemoveField(
            model_name='deliveryuser',
            name='vehicleType',
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='aadharBack',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/aadhar/back/'),
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='aadharFront',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/aadhar/front/'),
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='aadharNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='drivingLicenseBack',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/license/back/'),
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='drivingLicenseFront',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/license/front/'),
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='drivingLicenseNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='livePhoto',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/live/'),
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='panCard',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/pan/'),
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='panNumber',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='deliveryuser',
            name='vehicleRC',
            field=models.ImageField(blank=True, null=True, upload_to='delivery/vehicle_rc/'),
        ),
        migrations.AlterField(
            model_name='deliveryuser',
            name='vehicleNumber',
            field=models.CharField(max_length=15),
        ),
    ]
